Employees(INTEGER ID UNIQUE AUTOINCREMENT, TEXT NAME, TEXT POSITION);
Customers(INTEGER ID UNIQUE AUTOINCREMENT, TEXT NAME, TEXT DATA, TEXT PURCHASE_ID);
Sales(INTEGER ID, INTEGER EMP_ID, REAL MONEY, TEXT DATE);